### ISSUE TITLE
Failed updates on Fedora Server 34

### ISSUE THREAD

**Issue by agottschling** [doonze/EmbyUpdate#11]
As of recently, EmbyUpdate hasn't been successfully completing updates when ran automatically by systemd. This also causes the server to remain shutdown, as the script doesn't restart the server after a failed update.

Please let me know what logs or help I can provide. I know that Fedora (and other RedHat-like systems) aren't easy to deal with in this regard. 
Thanks in advance

**Comment by doonze** [comment]
Make sure you have the latest version installed. That would be 3.6. I merged some code into version 3.3 accidentally from another contributor and it broke all self-updating installs.

**Comment by doonze** [comment]
Also, this is a good chance for me to find out something, does Fedora NEED the server shut down, then restarted? Debian does not, as the dpkg process handles that when installing deb packages. It works with systemd to do all that work. I could spool up a Fedora VM and find out I suppose, but if you can verify that would be a big help!

I'm also going to add an enhancement tag to this, at one time I had it not checking for install failure till AFTER restarting the server, but I think a few years ago I added more exception logic and may have broken that. BETA has changed the way I do a lot of things, and I need to review how I'm handling install failures in BETA. I've been testing BETA for a month or so now, and we've had a number of updates since that went fine. If this is still an issue it will be corrected in BETA before I move it to stable.

**Comment by agottschling** [comment]
So, As for version, I'm running 3.6. I did have to manually reinstall. It also seems to be affected by timers. If systemd triggers the service to start based on a timer, it seems to fail. That might be my imagination though

Also, Here's the log it produced after the last run as captured by the systemd journal. 
```
3:35 AM embyupdate.service: Consumed 4.160s CPU time. systemd
3:35 AM Finished EmbyUpdater. systemd
3:35 AM embyupdate.service: Deactivated successfully. systemd
3:35 AM Download failed!! Exiting! python3
3:35 AM Starting Package download... python3
3:35 AM <11/25/21 03:35:16> EmbyUpdate: Starting update...... python3
3:35 AM <11/25/21 03:35:16> EmbyUpdate: Most recent online version is 4.6.7.0-Stable and current installed version is 4.6.6.0-Stable. We're updating Emby. python3
3:35 AM Could not open: /var/cache/dnf/commandline-f24b2296296d9941/packages/emby-server-rpm_4.6.7.0_x86_64.rpm python3 
3:35 AM Can not load RPM file: /var/cache/dnf/commandline-f24b2296296d9941/packages/emby-server-rpm_4.6.7.0_x86_64.rpm. python3
3:35 AM emby-server-rpm_4.6.7.0_x86_64.rpm 15 MB/s | 128 MB 00:08 python3
3:35 AM Last metadata expiration check: 1:38:11 ago on Thu 25 Nov 2021 01:57:06 AM EST. python3
3:35 AM Starting EmbyUpdater... systemd
```
As for dnf, I want to say that dnf will stop the service, but I haven't tried it myself.

**Comment by agottschling** [comment]
UPDATE: I just pulled the scripts from the RPM. See below
```
agottschling@MediaServer ~> rpm -qv --scripts emby-server
pretrans scriptlet (using /bin/sh):
systemctl stop emby-server > /dev/null 2>&1 || true
systemctl disable emby-server > /dev/null 2>&1 || true
posttrans scriptlet (using /bin/sh):
getent group emby > /dev/null 2>&1 || groupadd -r emby
getent passwd emby > /dev/null 2>&1 && usermod -c 'Emby Server' -g emby -d /var/lib/emby -m -s /usr/sbin/nologin emby
getent passwd emby > /dev/null 2>&1 || (useradd -r -c 'Emby Server' -g emby -d /var/lib/emby -m -s /usr/sbin/nologin emby && passwd -l emby > /dev/null && chown emby:emby -R /var/lib/emby)
getent group video > /dev/null 2>&1 && usermod -aG video emby
getent group render > /dev/null 2>&1 && usermod -aG render emby
systemctl daemon-reload > /dev/null
systemctl enable emby-server > /dev/null 2>&1 || true
systemctl start emby-server > /dev/null 2>&1 || true
```

**Comment by doonze** [comment]
Run this manually and let me know what happens, It's something in this causing the failure. Maybe a permissions issue? 

`dnf -y install https://github.com/MediaBrowser/Emby.Releases/releases/download/4.6.7.0/emby-server-rpm_4.6.7.0_x86_64.rpm`

I just tested this on my debian with wget, and the address works. From your logs, this is the relevant part:

`3:35 AM Could not open: /var/cache/dnf/commandline-f24b2296296d9941/packages/emby-server-rpm_4.6.7.0_x86_64.rpm python3 
3:35 AM Can not load RPM file: /var/cache/dnf/commandline-f24b2296296d9941/packages/emby-server-rpm_4.6.7.0_x86_64.rpm. python3`

I just can't tell if it can't download the file, or can't access it. This smells like permissions though.

**Comment by doonze** [comment]
As for dnf, I'm pretty sure it will stop/start the server on its own, so you don't need to stop/start it manually in the script. Your second log confirms this for me. the disable/enable and demon-reload are not coming from my script, so dnf is doing all of that on it's own.

**Comment by agottschling** [comment]
So, running that command interactively causes no errors, and the system updates the package correctly and restarts the server. I think you may be on to something. Is this all you're calling from python? or are you downloading the package first and then telling dnf where it is?

EDIT: I forgot to mention, if I started the service manually using systemctl, rather than having it triggered by a timer, it completes the update successfully. It may be something to do with the timer and how it's triggering the service, but I can't validate that. Also, I checked that directly that the error referred to, and it was empty with permissions for root.

Also, I think you're right in regards to dnf causing the service to stay disabled. However, the service is stopping at the exact same time that I'm running EU from systemd. Not saying that it's for sure the script, but wanted to share the observation.

**Comment by doonze** [comment]
The command I gave you is copied exactly from the EU code, that is exactly the command EU is issuing. Since it's working issuing it manually we know the command is good. If I'm understanding, you can run EU from systemctl manually as well, and It works? For example `sudo systemctl start embyupdate` works?

If EU finished cleanly, it would have updated the config file with the latest version, and it would now stop trying to update until a new version is released. You can modify the config file and manually change the version number to something different to get it to try to update again for testing.

I still think what we're getting here is permission errors. One thing I would try is to force the EU service to run as root. When you say you ran it manually and it worked, that also speaks to permission issues. Try this, update your service file with `User=root` and see what happens, like so:

```
[Unit]
Description=EmbyUpdate script

[Service]
User=root
Type=oneshot
ExecStart=/usr/bin/python3 /usr/local/bin/embyupdate/embyupdate.py
StandardOutput=append:/var/log/embyupdate/embyupdate.log
StandardError=append:/var/log/embyupdate/embyupdate.log
```

Then do a `sudo systemctl daemon-reload `. Let the timer fire it off and see if you still get the errors. Like I said above, if you got EU to run without fail manually, you'll have to modify the config file and delete the current version number of Emby to get it to try and update again.

**Comment by agottschling** [comment]
So, the plot thickens, I'm already running EU as root, and as a oneshot service. My service file looks almost exactly the same as the excerpt you provided (See below). Also, I only tested it by kicking off EU using `systemctl start`. I don't run the python script manually. Any thoughts?
```

[Unit]
Description=EmbyUpdater
Wants=embyupdate.timer

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 /root/EmbyUpdate/embyupdate.py
User=root

[Install]
WantedBy=multi-user.target
```
```

[Unit]
Description=Runs EmbyUpdate on a timer daily
Requires=embyupdate.service

[Timer]
Unit=embyupdate.service
OnCalendar=*-*-* 3:35:00

[Install]
WantedBy=timers.target
```

**Comment by agottschling** [comment]
@doonze Any thoughts on the above?

**Comment by doonze** [comment]
I don't, it makes no sense that it works fine if you run the `systemctl start embyupdate` but not when the timer is used. The only thing I can come up with is the timer is using its own permissions, but I would think those would be root. Maybe a Fedora forum or something posted on the systemd boards would help shed light on it? You can try running it as cron. It works just as well, the only reason I even suggest systemd at all is that seems to be where linux is going.

**Comment by agottschling** [comment]
The only thing I can potentially come up with is that EU's base directory is in /root. I'll see what happens if I move it to a less privileged directory like /opt

**Comment by doonze** [comment]
I have had issues with things in /root. It does have some weird behavior sometimes. I don't think I've ever tried running a script from /root with systemd. 

Let me know what you find.

**Comment by doonze** [comment]
Closing as there have been no updates in a while. Hoping it got fixed.
