### ISSUE TITLE
Error trying to create the config file.  

### ISSUE THREAD

**Issue by MaDTaZ** [doonze/EmbyUpdate#8]
Running Version 3.3 on LinuxMint. I had it working perfectly now stopped working 

Please review above choices and type CONFIRM to continue or c to cancel update and install! [CONFIRM/c] CONFIRM
Traceback (most recent call last):
  File "configupdate.py", line 173, in <module>
    config = ConfigParser()
TypeError: 'module' object is not callable

**Comment by doonze** [comment]
This was due to some undetected errors in a pull request I merged and my lack of testing as well as I should have. Unfortunately, since the self updater was effected all installed scripts updated themselves to the broken code and are...well... broken until manually updated to version 3.5. :( :( :( :( 

If you install 3.5 back over your current install, all should work again as intended. I sincerely apologize to you and everyone else affected for my lack of catching the error before it got pushed and broke the selfupdate process. It was my first time merging a pull request and I had thought I had just merged certain commits (that WERE tested) and not all the commits (some that had NOT been tested). I'll never make THAT mistake again!

**Comment by MaDTaZ** [comment]
Thanks

**Comment by MaDTaZ** [comment]
Look like I dont have my config.ini anymore but give me this error 
sudo python3 embyupdate.py --config

Config update started....

  File "configupdate.py", line 170
    config = configparser.ConfigParser())
                                        ^
SyntaxError: unmatched ')'
 
Running
sudo python3 embyupdate.py -v
EmbyUpdate 3.5

**Comment by hstorey219** [comment]
Hi There,
Got the same error as MaDTaZ, line 170

**Comment by MaDTaZ** [comment]
#9  Pull Request
edited the  configupdate.py line 170

config = configparser.ConfigParser())
to
config = configparser.ConfigParser()

I am good now  
Edited and did a pull request not sure if I did it right!  First time I ever fixed something lol

**Comment by doonze** [comment]
That's for the pull request fix, it's been rolled and is live. I didn't lose my config file and as I was doing copy/paste of the fixes I didn't catch it as I didn't run configupdate.py. That's my bad, but since it worked everywhere else I just assumed it was ok. That's what you get for assuming!

**Comment by doonze** [comment]
> Hi There,
> Got the same error as MaDTaZ, line 170

You can either download the latest version and unzip it over your existing version or manually make the change MaDTaZ mentioned, then run the script. It will then get in sync with the latest version.

**Comment by MaDTaZ** [comment]
That fixed it I was able to do everything 

<09/17/21 07:35:11> EmbyUpdate: We're up to date!  Current and Online versions are at 4.7.0.11-Beta. Exiting.
***
<09/17/21 07:35:11> EmbyUpdate(self): App is up to date!  Current and Online versions are at v3.6-Stable. Exiting!

Thanks for your work and quick responses.
